In [1]:
import numpy as np

In [2]:
# Learning 1D, 2D and multi-dimensional arrays
array_1 = np.array([10,20,30])
array_1

array([10, 20, 30])

In [3]:
array_2 = np.array([[1,2,3,], [4,5,6]])
array_2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
type(array_1)
type(array_2)

numpy.ndarray

In [7]:
array_3 = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[12,23,34], [45,56,67], [78,89,90]]])
array_3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[12, 23, 34],
        [45, 56, 67],
        [78, 89, 90]]])

In [8]:
array_2.shape    # this gives row and column

(2, 3)

In [9]:
array_3.shape, array_1.shape   # this for 3D array will give 2arrays, 3rows and 3column

((2, 3, 3), (3,))

In [10]:
array_1.ndim, array_2.ndim, array_3.ndim

(1, 2, 3)

In [11]:
array_1.size, array_2.size, array_3.size

(3, 6, 18)

Array can be converted into dataframe using Pandas.

In [13]:
import pandas as pd
df1 = pd.DataFrame(array_1)

In [14]:
df1

0
0  10
1  20
2  30

In [16]:
df2 = pd.DataFrame(array_2)
df2

0  1  2
0  1  2  3
1  4  5  6

In [20]:
df3 = pd.DataFrame(array_3.reshape(3,6))
df3

0   1   2   3   4   5
0   1   2   3   4   5   6
1   7   8   9  12  23  34
2  45  56  67  78  89  90

In [21]:
ar_zeros = np.zeros(5)
ar_zeros

array([0., 0., 0., 0., 0.])

In [26]:
ar_ones = np.ones(4)
ar_ones

array([1., 1., 1., 1.])

In [27]:
ar_ones.shape, ar_zeros.shape

((4,), (5,))

In [37]:
arr1 = np.arange(3,31, 3)
arr1

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [41]:
randarr1 = np.random.randint(10,20,size = (3,4))
randarr1

array([[11, 16, 15, 12],
       [15, 11, 18, 10],
       [15, 14, 10, 12]])

In [43]:
randarr2 = np.random.random((4,7))
randarr2

array([[0.33106457, 0.05727364, 0.20795173, 0.20931594, 0.24864811,
        0.04406193, 0.11084105],
       [0.28417665, 0.10469258, 0.78092725, 0.06266392, 0.00835724,
        0.10970388, 0.88847698],
       [0.32920443, 0.09383073, 0.6092393 , 0.70251673, 0.73172754,
        0.02983008, 0.22601818],
       [0.88077078, 0.23630148, 0.69350718, 0.67551413, 0.77072884,
        0.79768631, 0.09394562]])

In [44]:
randarr3 = np.random.rand(4,7)
randarr3

array([[0.99935895, 0.9139324 , 0.19508674, 0.74532632, 0.14279656,
        0.0827203 , 0.33644948],
       [0.98684302, 0.68432337, 0.89484513, 0.4435135 , 0.61827153,
        0.35492785, 0.91880676],
       [0.94159794, 0.3244179 , 0.79996666, 0.96593024, 0.63492393,
        0.25761322, 0.897997  ],
       [0.86069684, 0.76495667, 0.64753993, 0.39782214, 0.63004954,
        0.21168682, 0.57439993]])

In [53]:
np.random.seed(0)
randarr4 = np.random.randint(10,30,size=(4,5))
randarr4

array([[22, 25, 10, 13, 13],
       [17, 19, 29, 28, 14],
       [16, 22, 11, 16, 17],
       [24, 27, 15, 23, 18]])

In [54]:
randarr5 = np.random.randint(10,30,size=(2,3,4,5))
randarr5

array([[[[19, 29, 26, 29, 15],
         [25, 25, 10, 28, 13],
         [27, 29, 29, 29, 24],
         [17, 10, 11, 19, 10]],

        [[20, 13, 21, 28, 12],
         [10, 10, 14, 15, 16],
         [18, 27, 25, 14, 19],
         [20, 11, 11, 17, 19]],

        [[13, 16, 21, 24, 28],
         [10, 24, 13, 22, 20],
         [21, 14, 16, 14, 25],
         [13, 22, 14, 18, 24]]],


       [[[25, 13, 25, 23, 26],
         [27, 15, 19, 13, 10],
         [15, 10, 27, 28, 14],
         [12, 26, 13, 12, 20]],

        [[23, 26, 17, 19, 10],
         [20, 28, 21, 12, 12],
         [13, 13, 28, 24, 13],
         [27, 28, 24, 19, 11]],

        [[14, 20, 21, 18, 21],
         [12, 29, 26, 10, 10],
         [16, 29, 24, 20, 29],
         [18, 23, 12, 13, 12]]]])

In [65]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([5,6,7,8,9])
a1+a2
# a1-a2
# a1*a2
# a1/a2
# a1%a2

array([ 6,  8, 10, 12, 14])

In [66]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [67]:
np.exp(a2)

array([ 148.4131591 ,  403.42879349, 1096.63315843, 2980.95798704,
       8103.08392758])

In [69]:
np.sum(a1), sum(a2)

(15, 35)

In [70]:
np.mean(a2)

7.0

In [71]:
np.median(a1)

3.0

In [75]:
np.max(a1), np.min(a2)

(5, 5)

In [76]:
np.std(a1)

1.4142135623730951

In [77]:
np.var(a2)

2.0

In [79]:
np.sqrt(a2)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

STD = SQRT(VAR)

In [87]:
np.std(a1) == np.sqrt(np.var(a1))

True

In [96]:
array1 = np.array([[[1,2,3], [4,5,6]], [[12,23,34], [34,45,56]]])
array1.shape

(2, 2, 3)

In [103]:
array2 = np.array([[[1,2], [4,5], [7,8]], [[12,23], [34,45], [67,78]]])
array2.shape

(2, 3, 2)

In [106]:
array1 = array1.reshape(array2.shape)

In [107]:
array1*array2

array([[[   1,    4],
        [  12,   20],
        [  35,   48]],

       [[ 144,  529],
        [1156, 1530],
        [3015, 4368]]])

In [108]:
array1.shape

(2, 3, 2)

In [121]:
array4 = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[12,23,34], [34,45,56], [67,78,89]]])
array4.shape
array4 = array4.T
array4.shape

(3, 3, 2)

Comparison operations can be done:
<!-- >
<
==
!=
All these can be done -->

In [130]:
array1.shape == array4.shape

False

<img src = "image.jpg"/>

In [134]:
from matplotlib.image import imread

In [136]:
image = imread("image.jpg")

In [137]:
image

array([[[18, 28, 29],
        [19, 29, 30],
        [17, 27, 28],
        ...,
        [ 3, 15, 15],
        [ 3, 15, 15],
        [ 4, 16, 16]],

       [[17, 27, 28],
        [18, 28, 29],
        [17, 27, 28],
        ...,
        [ 1, 13, 13],
        [ 1, 13, 13],
        [ 2, 14, 14]],

       [[17, 27, 28],
        [18, 28, 29],
        [17, 27, 28],
        ...,
        [ 0, 12, 12],
        [ 0, 12, 12],
        [ 1, 13, 13]],

       ...,

       [[20, 24, 23],
        [20, 24, 23],
        [19, 25, 23],
        ...,
        [ 2,  7, 10],
        [ 2,  7, 10],
        [ 2,  7, 10]],

       [[17, 21, 20],
        [17, 21, 20],
        [16, 22, 20],
        ...,
        [ 2,  7, 10],
        [ 2,  7, 10],
        [ 2,  7, 10]],

       [[11, 17, 15],
        [12, 18, 16],
        [12, 18, 16],
        ...,
        [ 2,  7, 10],
        [ 2,  7, 10],
        [ 2,  7, 10]]], dtype=uint8)

In [138]:
image.size

2764800

In [140]:
image.shape

(720, 1280, 3)

In [6]:
import numpy as np
ar = np.array([1,2,3,4,0])

In [7]:
ar

array([1, 2, 3, 4, 0])

In [8]:
np.where(ar<3)

(array([0, 1, 4], dtype=int64),)

In [9]:
np.count_nonzero(ar)

4